version: '3'

services:
  DATABASE:
    image: postgres
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports:
      - 5432:5432
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    networks:
      - app_network
  server:
    build: ./server
    ports:
      - 8080:8080
    depends_on:
      - DATABASE
    environment:
      DB_CONNECTION_STRING: postgres://postgres:docker@db:5432/db
    networks:
      - app_network 
    volumes: 
      - "./back-end:/app"  
  client:
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
    